const menu=[
{title:['القهوة والحلويات','Coffee & Desserts'],groups:[
{title:['القهوة السوداء','BLACK COFFEE'],items:[['V60','V60','100/120'],['إسبريسو','Espresso','55'],['أمريكانو','Americano','60'],['قهوة تركي سنجل / دبل','Turkish Coffee S/D','35/55']]},
{title:['القهوة بالحليب الساخنة','HOT WHITE COFFEE'],items:[['لاتيه','Latte','80'],['كورتادو','Cortado','75'],['فلات وايت','Flat White','80'],['كابتشينو','Cappuccino','80'],['ماكياتو','Macchiato','65'],['قهوة فرنساوي','Frensh Coffee','45/60'],['قهوة بالبندق','Hazelnut Coffee','45/60'],['كراميل ماكياتو','Caramel Macchiato','90'],['سبانيش لاتيه','Spanish Latte','90'],['موكا (دارك / وايت)','Mocha (DARK/WHITE)','90/100']]},
{title:['مشروباتنا المميزة','SIGNATURE'],items:[['سبانيش لاتيه','Spanish Latte','100'],['سولتد كراميل','Salted Caramel','110'],['آيرش','IRISH','100'],['بلو كلاودي','Blue Cloudy','85'],['صن كلاودي','Sun Cloudy','85'],['ماتشا كلاودي','Matcha Cloudy','110'],['سولتد ماتشا','Salted Matcha','120'],['آل فيرادو','AL FERADO','90'],['فرابتشينو','Frappuccino','100'],['شوكولاتة مثلجة','ICED Chocolate','80'],['كركديه مثلج','ICED Karkidh','60']]},
{title:['المخبوزات والحلويات','BAKED&DESSERT'],items:[['كوكيز','Cookies','60','كلاسيك - ريد فيلفيت - دارك - نوتيلا','Classic - Redvelvet - Dark - Nutella'],['بروتين بار','Protin BAR','60'],['بروكيز','Brookies','70'],['تيراميسو كلاسيك','Tiramisu Classic','90'],['تيراميسو','Tiramisu','90','مانجو - توت أزرق - فراولة','Mango - Blueberry - Strawberry'],['سان سيباستيان','San Sebastian','85'],['مولتن كيك','Molten Cake','95'],['تشيز كيك','Cheese Cake','85']]}]},
{title:['المشروبات','Drinks'],groups:[
{title:['القهوة المثلجة','ICED COFFEE'],items:[['أمريكانو','Americano','70'],['لاتيه','Latte','85'],['كراميل ماكياتو','Caramel Macchiato','95'],['موكا (دارك / وايت)','Mocha (DARK/WHITE)','95/100']]},
{title:['ماتشا كيوبز','MATCHA CUBES'],items:[['ماتشا لاتيه','Matcha Latte','90'],['سبانيش ماتشا','Spanish Matcha','110'],['ماتشا بالفواكه','Matcha Fruits','120','فراولة - توت أزرق - مانجو - جوز هند','Strawberry - Blueberry - Mango - Coconut']]},
{title:['ماتشا بليندد','BLENDED'],items:[['ماتشا فرابيه','Matcha Frappe','95'],['سبانيش ماتشا','Spanish Matcha','120'],['سولتد ماتشا','Salted Matcha','120'],['ماتشا بالفواكه','Matcha Fruits','120','فراولة - توت أزرق - مانجو - جوز هند','Strawberry - Blueberry - Mango - Coconut']]},
{title:['قهوة بليندد','BLENDED COFFEE'],items:[['سبانيش','Spanish','110'],['سولتد كراميل','Salted Caramel','120'],['كراميل ماكياتو','Caramel Macchiato','100'],['موكا (دارك / وايت)','Mocha (DARK/WHITE)','100/110']]},
{title:['موهيتو','MOJITO'],items:[['نعناع','Mint','65'],['فراولة','Strawberry','65'],['رمان','Pomegranate','65'],['فرعون','Faraon','75'],['ليتشي','Lychee','90'],['خوخ','Peach','75'],['باشن فروت','Passion Fruit','85'],['توت أزرق','Blueberry','85'],['ميكس توت ريد بول','Mik Berries Redbull','115']]},
{title:['مشروبات ساخنة وشوكولاتة','HOT CLASSICS & CHOCOLATE'],items:[['شاي','Tea','25'],['شاي كرك','Karak Tea','60'],['شاي بالحليب والفراولة','Strawberyy Milk Tea','50'],['سحلب (كلاسيك / مكسرات)','Sahlab (Classic/Nuts)','50/75'],['هوت شوكليت أصلي','Hot Chocolate Original','60'],['هوت شوكليت بالنكهات','Hot Chocolate Flavor','80','أوريو - نوتيلا - كيندر','Oreo - Nutella - Kinder'],['هوت سايدر','Hot Cider','50'],['هوت كراميل','Hot Caramel','60']]}]},
{title:['الميلك شيك والإفطار','Milkshakes & Breakfast'],groups:[
{title:['ميلك شيك','MILK SHAKE'],items:[['ميلك شيك أوريو','Milk Shakes Oreo','90'],['ميلك شيك كلاسيك','Milk Shakes Classics','75','فانيليا - شوكولاتة - كراميل','Vanilla - Chocolate - Caramel'],['ميلك شيك فواكه','Milk Shakes Fruits','80','مانجو - فراولة - توت أزرق','Mango - Strawberry - Blueberry'],['ميلك شيك ميكس شوكولاتة','Milk Shakes Mix Chocolate','100','أوريو - كيندر - نوتيلا - لوتس','Oreo - Kinder - Nutella - Lotus'],['ميلك شيك فستق','Milk Shake Pistachio','110']]},
{title:['فواكه بليندد','BLENDED FRUITS'],items:[['بينا كولادا','Pina Colada','80'],['مانجو باشن','Mango Passion','80'],['مانجو ليتشي','Mango Lychee','90'],['بينكي','Pinky','80'],['ريد ليتشي','Red Lychee','90'],['تريبل بي','Tripple P','80']]},
{title:['المشروبات الغازية','SOFT DRINKS'],items:[['V7 / في كولا','V7 / Vcola','25'],['تويست','TWIST','35'],['ريد بول','Redbull','90'],['مياه معدنية صغيرة','Small Minral Water','10']]},
{title:['كرواسون','CROISSANT'],items:[['كرواسون سادة','Plain Croissant','60'],['كرواسون لحم بقري مدخن','Croissant Smoked Beef','100'],['كرواسون ديك رومي مدخن','Croissant Smoked Turkey','95'],['كرواسون ميكس جبن','Croissant Mix Chesse','75']]},
{title:['ساندوتشات','SANDWICHES'],note:['بانيني - فيينا - براون - فوكاتشيا','PANINI - VIENNA - BROWN - FOCACCIA'],items:[['ديك رومي مدخن','Smoked Turkey','100'],['دجاج مدخن','Smoked Chicken','100'],['ميكس جبن','Mix Cheese','80'],['حلومي','Halloumi','90']]}]}
];
let lang='en';try{lang=localStorage.getItem('bh-language-v2')||'en'}catch{}if(!['ar','en'].includes(lang))lang='en';
function render(){const k=lang==='ar'?0:1;document.documentElement.lang=lang;document.documentElement.dir=k===0?'rtl':'ltr';document.title=k===0?'BLACK HORSE | المنيو':'BLACK HORSE | Menu';document.querySelector('#menu-title').textContent=k===0?'المنيو':'Menu';document.querySelector('#count').textContent=k===0?'٣ صفحات':'3 pages';document.querySelector('#download').textContent=k===0?'تحميل المنيو الأصلي PDF':'Download original PDF';document.querySelector('#menu-nav').replaceChildren(...menu.map((p,i)=>{let a=document.createElement('a');a.href='#page-'+(i+1);a.textContent=p.title[k];return a}));const pages=document.querySelector('#pages');pages.replaceChildren();menu.forEach((p,i)=>{let section=document.createElement('section');section.id='page-'+(i+1);let label=document.createElement('h2');label.className='label';let num=document.createElement('span');num.textContent='0'+(i+1);label.append(num,document.createTextNode(p.title[k]));let sheet=document.createElement('div');sheet.className='sheet';let brand=document.createElement('div');brand.className='sheet-title';brand.textContent='BLACK HORSE';sheet.append(brand);if(i===2){let options=document.createElement('div');options.className='options';let title=document.createElement('h3');title.textContent=k===0?'اختار كوبك':'MAKE YOUR CUP';options.append(title);const choices=[{label:['اختيارات الحليب','MILK OPTIONS'],values:[['جوز هند','لوز','شوفان'],['Coconut','Almond','Oat']]},{label:['النكهات','FLAVORS'],values:[['أوريو','كيندر','نوتيلا','لوتس'],['Oreo','Kinder','Nutella','Lotus']]}];choices.forEach(choice=>{let block=document.createElement('div');block.className='option-block';let label=document.createElement('h4');label.textContent=choice.label[k];let values=document.createElement('div');values.className='option-values';choice.values[k].forEach(value=>{let chip=document.createElement('span');chip.textContent=value;values.append(chip)});block.append(label,values);options.append(block)});sheet.append(options)}p.groups.forEach(g=>{let group=document.createElement('div');group.className='group';let heading=document.createElement('h3');heading.textContent=g.title[k];group.append(heading);if(g.note){let n=document.createElement('p');n.className='group-note';n.textContent=g.note[k];group.append(n)}let list=document.createElement('ul');g.items.forEach(item=>{let row=document.createElement('li');let name=document.createElement('div');let text=document.createElement('span');text.textContent=item[k];name.append(text);if(item[3]){let sub=document.createElement('small');sub.textContent=item[k===0?3:4];name.append(sub)}let price=document.createElement('span');price.className='price';price.textContent=item[2];row.append(name,price);list.append(row)});group.append(list);sheet.append(group)});section.append(label,sheet);pages.append(section)});document.querySelectorAll('[data-lang]').forEach(b=>{b.setAttribute('aria-pressed',String(b.dataset.lang===lang))})}
document.querySelectorAll('[data-lang]').forEach(b=>b.addEventListener('click',()=>{lang=b.dataset.lang;try{localStorage.setItem('bh-language-v2',lang)}catch{}render()}));render();
